#!/usr/bin/env bash
#
#
VERSION="1.1.0"
sudo cp -f kenwood/710.sh /usr/local/bin/
sudo cp -f kenwood/*.py /usr/local/bin/
sudo cp -f kenwood/*.png /usr/share/pixmaps/
sudo rm -f /usr/local/bin/kenwoodTM.py

